### ISSUE TITLE
I face an issue where calculating failed. I don't know what went wrong

### ISSUE THREAD

**Issue by vu-dao-93** [hanzki/rsu-tax-calculator#12]
I followed the steps correctly, but got this error. The warning above shows up when I uploaded my individual history.
![Screenshot 2023-12-17 at 17 24 41](https://github.com/hanzki/rsu-tax-calculator/assets/7025841/1fb89793-8105-4938-a024-bed464d32693)

**Comment by hanzki** [comment]
You might see an error like that if the equity awards account export
doesn't include all transactions. By default schawb only includes the last
6 months in the export. Note that after switching the time frame you need
to press the search button for the data to update. If you press the export
without pressing search first the export time frame won't update.

**Comment by vu-dao-93** [comment]
Thank you! I think I forgot to press Search. Reexport the correct equity award history fixes the issue.
